# Copyright (c) 2023, NVIDIA CORPORATION.  All rights reserved

#local machine

# Paths #
root: "/home/nicolas/Repulsive-score-distillation-RSD-/constrained_sampling/_exp"
load_img_id: False
save_evolution: True
evol_path: "evol"
output_path: "output"
save_ori: False
ori_path: "ground_truth"
save_deg: True
deg_path: "deg"
ckpt_root: "ckpts"

overwrite: True

num_steps: 200
start_step: 1000
end_step: 0
smoke_test: 4
logfreq: 200
seed: 1

