#### general settings
gpu_ids: [0]

#### network structures
KernelWizard:
  #pretrained: experiments/pretrained/GOPRO_wVAE.pth
  #pretrained: /home/mmardani/research/stable-diffusion-sampling-gitlab/pgdm/bkse/experiments/pretrained/kernel.pth
  #pretrained: /lustre/fsw/nvresearch/mmardani/source/latent-diffusion-sampling/pgdm/bkse/experiments/pretrained/kernel.pth
  pretrained: bkse/experiments/pretrained/GOPRO_wVAE.pth
  input_nc: 3
  nf: 64
  front_RBs: 10
  back_RBs: 20
  N_frames: 1
  kernel_dim: 512
  use_vae: true
  KernelExtractor:
    norm: none
    use_sharp: true
    n_blocks: 4
    padding_type: reflect
    use_dropout: false
  Adapter:
    norm: none
    use_dropout: false
