# Copyright (c) 2023, NVIDIA CORPORATION.  All rights reserved

name: "reddiff_parallel"
deg: "deno"
awd: True
cond_awd: False
grad_term_weight: 0.5
denoise_term_weight: "linear"    #"linear", "sqrt", "log", "square", "trunc_linear", "const", "power2over3"
sigma_y: 0.0
eta: 0.0
lr: 0.1