# Copyright (c) 2023, NVIDIA CORPORATION.  All rights reserved

_target_: models.guided_diffusion.script_util.create_model
in_channels: 3
out_channels: 3
num_channels: 128
num_heads: 4
num_res_blocks: 1
attention_resolutions: "16"
dropout: 0.0
resamp_with_conv: True
learn_sigma: True
use_scale_shift_norm: true
use_fp16: false
resblock_updown: true
num_heads_upsample: -1
var_type: 'fixedsmall'
num_head_channels: 64
image_size: 256
class_cond: false
use_new_attention_order: false
ckpt: "ffhq_256"
